name: oz_scrape

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
#     - cron: "5 */2 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master                                                               
      - name: Set up Python 3.8                               
        uses: actions/setup-python@master                               
        with:                                 
          python-version: 3.8                                                   
  
      - name: 💿 Install Requirements                             
        run: pip install -r reqs.txt
        
      - name: 🍳 Scrape Federal Health
        run: python health_scraper.py
        
      - name: 🚀 Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
